### ISSUE TITLE
Robotic Arm Gripper CAD Files

### ISSUE THREAD

**Issue by TGiles1998** [Neumi/liion_checker#1]
Hi,

Thank you so much for your work. Are the CAD files for the robot gripper available?

Many thanks,

Thomas

**Comment by Neumi** [comment]
Hey Thanks for asking!
I just exported them and will upload them in the next few minutes. :)

**Comment by Neumi** [comment]
closed 
relates https://github.com/Neumi/liion_checker/commit/1741b37f245a0d8a992f4f4c5b05e0aa9a31439e
and https://github.com/Neumi/liion_checker/commit/03a477d1716eab863f564af22d5e59732eaa1768

**Comment by TGiles1998** [comment]
Is it possible to have .step files as well? Many thanks,

Thomas

**Comment by Neumi** [comment]
It's an older project and was designed in SketchUp. Sorry :/
